---
- name: Demonstrate different loop types
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Standard loop
      ansible.builtin.debug:
        msg: "Item: {{ item }}"
      loop: "{{ simple_list }}"
      # Output: Item: apple
      # Output: Item: banana
      # Output: Item: cherry

    - name: With_items example
      ansible.builtin.debug:
        msg: "Name: {{ item.name }}, Value: {{ item.value }}"
      with_items: "{{ sample_list }}"
      # Output: Name: item1, Value: 100
      # Output: Name: item2, Value: 200
      # Output: Name: item3, Value: 300

    - name: With_dict example
      ansible.builtin.debug:
        msg: "Key: {{ item.key }}, Description: {{ item.value.desc }}"
      with_dict: "{{ sample_dict }}"
      # Output: Key: key1, Description: First item
      # Output: Key: key2, Description: Second item
      # Output: Key: key3, Description: Third item 