---
- name: Demonstrate combined filters
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Get names of enabled items
      ansible.builtin.debug:
        msg: "Enabled item names: {{ sample_list | selectattr('enabled', 'true') | map(attribute='name') | list }}"
      # Output: Enabled item names: ['item1', 'item3']

    - name: Get total value of enabled items
      ansible.builtin.debug:
        msg: "Total enabled value: {{ sample_list | selectattr('enabled', 'true') | map(attribute='value') | sum }}"
      # Output: Total enabled value: 400 